name: feal_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^1.0.0
  dio: ^4.0.0
  flutter_html: ^0.8.2
  flutter_dotenv: ^3.1.0
  provider: ^5.0.0
  http: ^0.13.1
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+4
  flutter_spinkit: "^4.1.2"


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  url_launcher: ^5.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - .env
    - images/z1.jpeg
    - images/z2.jpeg
    - images/z3.jpeg
    - images/Logo2.png
    - images/products/majica.jpeg
    - images/products/bosch.jpeg
    - images/products/cd.jpeg
    - images/products/makita.png
    - images/products/tene.jpeg
    - images/products/kaiš.jpeg
    - images/toolscat/drill.png
    - images/toolscat/drilling.jpeg
    - images/toolscat/hamer.png
    - images/categories/1.png
    - images/categories/2.png
    - images/categories/3.png
    - images/categories/4.png
    - images/categories/9.png
    - images/categories/10.png
    - images/categories/11.png
    - images/categories/12.png
    - images/categories/13.png
    - images/categories/17.png
    - images/categories/18.png
    - images/categories/19.png
    - images/categories/20.png
    - images/categories/21.png
    - images/categories/22.png
    - images/categories/23.png
    - images/categories/24.png
    - images/categories/25.png
    - images/categories/26.png
    - images/categories/27.png
    - images/categories/desktops/1.jpg
    - images/categories/desktops/3.jpg
    - images/categories/desktops/4.jpg
    - images/categories/notebooks/5.jpg
    - images/categories/notebooks/7.jpg
    - images/categories/notebooks/8.jpg
    - images/categories/notebooks/9.jpg
    - images/categories/notebooks/11.jpg
    - images/categories/notebooks/12.jpg
    - images/categories/software/13.jpg
    - images/categories/software/14.jpg
    - images/categories/software/15.jpg
    - images/categories/shoes/30.jpg
    - images/categories/shoes/32.jpg
    - images/categories/shoes/35.jpg
    - images/categories/clothing/36.jpg
    - images/categories/clothing/37.jpg
    - images/categories/clothing/38.jpg
    - images/categories/clothing/39.jpg
    - images/categories/accessories/41.jpg
    - images/categories/accessories/42.jpg
    - images/categories/accessories/43.jpg
    - images/categories/digital downloads/44.jpg
    - images/categories/digital downloads/45.jpg
    - images/categories/digital downloads/46.jpg
    - images/categories/cordless drill/56.jpg
    - images/categories/cordless drill/58.jpg
    - images/categories/hammer drill/60.jpg
    - images/categories/hammer drill/62.jpg
    - images/categories/drilling machine/64.jpg
    - images/categories/drilling machine/67.jpg
    - images/categories/circular saw/68.jpg
    - images/categories/circular saw/70.jpg
    - images/categories/reciprocating saw/72.jpg
    - images/categories/reciprocating saw/74.jpg
    - images/categories/multi-tool/76.jpg
    - images/categories/multi-tool/78.jpg
    - images/categories/battery lamp/80.jpg
    - images/categories/all products/1.jpg
    - images/categories/all products/3.jpg
    - images/categories/all products/4.jpg
    - images/categories/all products/5.jpg
    - images/categories/all products/7.jpg
    - images/categories/all products/8.jpg
    - images/categories/all products/9.jpg
    - images/categories/all products/11.jpg
    - images/categories/all products/12.jpg
    - images/categories/all products/13.jpg
    - images/categories/all products/14.jpg
    - images/categories/all products/15.jpg
    - images/categories/all products/16.jpg
    - images/categories/all products/18.jpg
    - images/categories/all products/19.jpg
    - images/categories/all products/20.jpg
    - images/categories/all products/21.jpg
    - images/categories/all products/22.jpg
    - images/categories/all products/23.jpg
    - images/categories/all products/25.jpg
    - images/categories/all products/26.jpg
    - images/categories/all products/28.jpg
    - images/categories/all products/29.jpg
    - images/categories/all products/30.jpg
    - images/categories/all products/32.jpg
    - images/categories/all products/35.jpg
    - images/categories/all products/36.jpg
    - images/categories/all products/37.jpg
    - images/categories/all products/38.jpg
    - images/categories/all products/39.jpg
    - images/categories/all products/41.jpg
    - images/categories/all products/42.jpg
    - images/categories/all products/43.jpg
    - images/categories/all products/44.jpg
    - images/categories/all products/45.jpg
    - images/categories/all products/46.jpg
    - images/categories/all products/49.jpg
    - images/categories/all products/50.jpg
    - images/categories/all products/52.jpg
    - images/categories/all products/56.jpg
    - images/categories/all products/58.jpg
    - images/categories/all products/60.jpg
    - images/categories/all products/62.jpg
    - images/categories/all products/64.jpg
    - images/categories/all products/67.jpg
    - images/categories/all products/68.jpg
    - images/categories/all products/70.jpg
    - images/categories/all products/72.jpg
    - images/categories/all products/74.jpg
    - images/categories/all products/76.jpg
    - images/categories/all products/78.jpg
    - images/categories/all products/80.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
